### ISSUE TITLE
Missing LICENSE or COPYING

### ISSUE THREAD

**Issue by ghost** [ben-marshall/doxygen-themes#1]
Quoting https://choosealicense.com/no-license/
>When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 

I think you published your themes on github expecting somebody (for example @foxcpp) will use it, but they actually can't due to copyright law. If so it would be nice for you to add license to your themes. Hint: https://choosealicense.com/non-software/

**Comment by ben-marshall** [comment]
Thank you for the prompt - I've added the CC-BY-4.0 license :-)
